### PR TITLE
small JS fixes

### PR DESCRIPTION
**Pull request by Pomax**
Heya, 

I ran across your code (you're my hero of the week, it is miraculous how hard it is to find an actual complete, generic implementation of BSplines, let along in JavaScript!) and noticed a few uses of JS that don't do what one might think they do in modern JS, so I did a small bit of rewriting and documenting, hopefully to the benefit of the library.

About the changes:

`New Array(len)` doesn't actually do in JS what it does in most languages: It does _not_ allocate an array of a specific size, it simply creates an array object and sets its length property to the indicated value, similar to doing `arr = []; arr.length = 10`. Setting the `length` property doesn't actually allocate any contiguous memory or the like, it literally just sets an int value in the object metatdata. It was added way back when `document.write` was still a good idea, and never got rescinded.

One thing you can use it for is trick code, like `weights = new Array(n+1).join(',').split(',').map(v => 1)`, which builds a new array without allocation, then takes advantage of the iteration process (which relies purely on `length`) to join up the array into a string `,,,,,,,` of length `n`, then splits it up again to form a _real_ array ['','','','',...] of length `n`, and then maps that array to some value set. In the preceding code, an array of ones of length `n`, but it's far less readable, and far more expensive, than a simple for loop =)

I've also made some of the variables that are function scoped explicitly function scoped, because code in strict mode will throw errors over those repeated `var i` etc. declarations in the for loops. `var` creates a function-scoped variable, so two consecutive `for (var i=0; ...)` will lead to a redeclaration error (along the lines of "variable already exists"). ES6 has `let` these days, but there are still plenty of systems that use a Node that's older than v4, so updating the code to ES6 syntax seems premature at best, and a breaking change on average.

### CODE REVIEW

**Comment by thibauts** [comment]
Hey Max, thanks for your thoughtful input. I just merged your PR, published to npm and globally added you as an owner on this project. Feel free to push code, though I'll be glad if the writing that goes with the code gets published here too !

I'm happy you found this useful as I put a good deal of energy in it, first to wrap my head around the algorithm and general spline theory, then to make it clean and clear.

Have a good day !

**Comment by Pomax** [comment]
Heh, just 'Pomax', not short or long for anything =)

Thanks for adding me as global owner - I run a Primer on Bezier Curves (over on https://pomax.github.io/bezierinfo) and people have been asking me when I'm adding sections on B-Splines and NURBS for... well, years, now, so I finally decided to have a look and see what was available to make explaining them easier, and found your excellent package. I initially tried to write my own, but for whatever reason couldn't get points to generate correctly for non-uniform open curves. Admittedly, I only spent a day on it, but finding your code was so much better: you wrote some really concise, yet easy to read and beautiful code!

**Comment by thibauts** [comment]
Heh, I intended to write Mike, but my fingers slipped / took over :)

Of course ... I saw your primer on HN a while ago, was quite baffled by the hard work and dedication. Really, hats off, and thank you. When I found it I scrolled to try to find pieces that could help me compute B-spline derivatives, something I have tried to do after publishing this module but without success. I was mostly interested in derivatives, knot insertion and curve intersection. The goal was to provide simple tools to make CAD in the browser a little bit more within reach of the community. I hit a wall trying to understand blossoms and ran out of free time. Hopefully open-sourcing this code will enable others to take over and push it further.

One small thing I regret here is having used `order` instead of `degree`, the later seemingly being the norm.

**Comment by Pomax** [comment]
Small things are easy to do: I filed https://github.com/thibauts/b-spline/pull/7 as a refactor for that, swapping `order` for `degree` in both the JS and the README.md

I need to get to terms with blossoms myself; as long as I've worked with Beziers, some parts of it are still parts I simply never looked at! (lots to explore, lots of related topics distracting you =D)

**Comment by thibauts** [comment]
Just pushed an update to the `order-degree-refactor` branch, plus I got a working implementation of derivatives of Nth order (only checked results for first order yet, though). I still have to make it work with homogeneous coordinates, but well. [This](https://books.google.fr/books?id=xFuhIl1rb2sC&pg=PA349&lpg=PA349#v=onepage&q&f=false) helped me understand the process. I'll try to push the code later today (it's 1pm here).

**Pull request merged**
